<a href="https://colab.research.google.com/github/priyadarsh99/IITM_Machine_Learning/blob/main/Demonstration_of_sklearn_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Loaders**

In [ ]:
from sklearn.datasets import load_iris
data = load_iris()

This returns a Bunch object data which is a dictionary like object with the following attributes:


*   `data`, which has the feature matrix
*   target, which is the label vector
* `feature_names` contain the names if the fetures.
* `target_names` contain the names of the classes.
* `DESCR` has the full description of the dataset.
* `filename` has the path to the location of the data.



In [ ]:
type(data)

sklearn.utils.Bunch

###**We can Access them one by one and examine their contents, for example we can access `feature_names` as follows:**

In [ ]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

###**Examining name of the labels of the dataset**

In [ ]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

#### there are three different classes of labels: setosa, versicolor, virgininca

##**Accessing the feature matrix:**

lets's look at the first five examples in the feature matrix

In [ ]:
data.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

#### there are 4 features per example(datapoint)

In [ ]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

###**Knowing the shape of the dataset**

In [ ]:
data.data.shape
#shape of feature matrix


#it has 150 examples(datapoints) and each example(datapoint) has 4 features

(150, 4)

###**Accessing the label vector of the dataset & knowing it's shape**

In [ ]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

###**There are 50 examples each from three classes: 0,1,2**


In [ ]:
data.target.shape
#shape of label vector

(150,)

###**To read ADDITIONAL DOCUMENTATION or HELP we use ?**

In [ ]:
?load_iris

#**Obtaining the feature matrix and label/target from `load_iris` and other loaders by putting: (in form of tuples)**
`return_X_y` argument to `True`

**just put return_X_y=True**

In [ ]:
feature_matrix, label_vector = load_iris(return_X_y=True) 
#here we are loading the dataset in the form of ndarray
#feature_matrix stores the features
#label_vector stores the label
#in the form of ndArray
print('Shape of the feature matrix:',feature_matrix.shape)
print('Shape of the label vector:',label_vector.shape)

Shape of the feature matrix: (150, 4)
Shape of the label vector: (150,)


##**Converting the ndArray to dataframe**

In [ ]:
import pandas as pd
df_iris = pd.DataFrame(data=feature_matrix,columns =['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)'] )
#loading the feature as dataframe

df_iris["Target"] = pd.DataFrame(data=label_vector,columns= ["Target"])
#adding the target vector to the dataframe

In [ ]:
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

#**Converting the sklearn dataset directly into dataframe**

**here we are directly converting from `Bunch` to `dataframe`**

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris() #loaded the dataset in the type `Bunch` object

df_iris = pd.DataFrame(data=iris.data,columns = iris.feature_names)
#adding the features to the dataframe by putting data = iris.data
#and names by columns = iris.feature_names

df_iris["Target"]=iris.target
#adding the target label to the dataframe

In [ ]:
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

##**CHECKING THE CLASSIFICATION COUNT IN THE DATASET OF CLASSIFICATION**

In [ ]:
df_iris["Target"].value_counts()

#if we want to check how many datapoints belong to which class in the "classification dataset" 
#but first we convert the dataset from 'Bunch' object to 'DataFrame'

0    50
1    50
2    50
Name: Target, dtype: int64

#**Exercises**

##**Use the diabetes dataset, digits dataset, wine dataset, breast cancer dataset, linnerud dataset**


`load_diabetes` 

`load_digits`

`load_wine`

`load_breast_cancer`

`load_linnerud`







*   Load the dataset
*   Obtain the Bunch object
* Examine the Bunch object:
        1. Look at the description and documentation of the dataset
        2. Find out the shape of the feature matrix
        3. Look at the first five examples from the feature matrix.
        4. Find out the shape of the label matrix.
        5. Look at the labels of hte first five examples.
        6. Find out the names of the features.
        7. Find the names of class labels.








###**Diabetes Dataset**

###**Wine Dataset**

**1. Importing the loader**

In [ ]:
from sklearn.datasets import load_wine

**Accessing the documentation of the dataset**

In [ ]:
?load_wine
#documentation of the dataset

**2. Loading the dataset and obtaining a `Bunch` object**

In [ ]:
data = load_wine()
#loading the dataset as 'Bunch' object

**3. Examining the `Bunch` object.**

**Looking at the description of the dataset**

In [ ]:
data.DESCR
#description of the dataset

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                     

**Find the shape of the feature matrix**

In [ ]:
data.data.shape
#shape of the feature matrix

(178, 13)

**First five examples from the feature matrix**

In [ ]:
data.data[:5]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
        3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.437e+01, 1.950e+00, 2.500e+00, 1.680e+01, 1.130e+02, 3.850e+00,
        3.490e+00, 2.400e-01, 2.180e+00, 7.800e+00, 8.600e-01, 3.450e+00,
        1.480e+03],
       [1.324e+01, 2.590e+00, 2.870e+00, 2.100e+01, 1.180e+02, 2.800e+00,
        2.690e+00, 3.900e-01, 1.820e+00, 4.320e+00, 1.040e+00, 2.930e+00,
        7.350e+02]])

**Find the shape of the label vector**

In [ ]:
data.target.shape

(178,)

**First five examples of the label vector**

In [ ]:
data.target[:5]

array([0, 0, 0, 0, 0])

**Find the names of the features**

In [ ]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

**Find the name of the class labels**

In [ ]:
data.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

#**Fetchers**

###**Fetching california housing dataset**

**1. Importing the library and access the documentation.**

**Note: `fetch_*` also returns a `Bunch` object just like loaders**



In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
?fetch_california_housing

 **2. Loading the dataset and obtaining the `Bunch` object** 

In [ ]:
housing_data = fetch_california_housing()

**3.Examining the `Bunch` object:**

**Looking the description of the dataset**

In [ ]:
housing_data.DESCR

'.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block group\n        - HouseAge      median house age in block group\n        - AveRooms      average number of rooms per household\n        - AveBedrms     average number of bedrooms per household\n        - Population    block group population\n        - AveOccup      average number of household members\n        - Latitude      block group latitude\n        - Longitude     block group longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000

**Looking at the shape of the feature matrix**

In [ ]:
housing_data.data.shape

(20640, 8)

**First five examples of the feature matrix**

In [ ]:
housing_data.data[:5]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])

**Find the shape of the label vector**

In [ ]:
housing_data.target.shape

(20640,)

**First five examples of the label vector**

In [ ]:
housing_data.target[:5]

array([4.526, 3.585, 3.521, 3.413, 3.422])

**Find the name of the features**

In [ ]:
housing_data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

**Find the names of the labels**

In [ ]:
housing_data.target_names

['MedHouseVal']

#**`fetch_openml`**

**[openml.org](https://) is a public repository for machine learning data and experiments, that allows everybody to UPLOAD OPEN DATASETS**

###**Import the library and access the documentation.**

In [ ]:
from sklearn.datasets import fetch_openml 
?fetch_openml

**Note that this is an experimental API and is likely to change in the future releases.**

###**We'll use this API for loading MNIST dataset**

In [ ]:
X,y = fetch_openml('mnist_784', version=1, return_X_y=True)
print('Feature matrix shape:',X.shape)
print('Label shape:',y.shape)

Feature matrix shape: (70000, 784)
Label shape: (70000,)


###**Exercise**

`fetch_20newsgroups`

`fetch_kddcup99`

#**Generators**

###`make_regression`

In [ ]:
from sklearn.datasets import make_regression 
?make_regression

###**Example 1.**

####**Let's generate 100 samples with 5 features for a single label regression problem**

In [ ]:
X, y = make_regression(n_samples = 100, n_features=5, n_targets=1, shuffle=True, random_state=42)

####**It's good practice to set seed(random_state) so that we get to see repeatability in the experimentation**

In [ ]:
X.shape

(100, 5)

In [ ]:
y.shape

(100,)

In [ ]:
type(X),type(y)

(numpy.ndarray, numpy.ndarray)

###**Example 2**

####**Let's generate 100 samples with 5 features for multiple regression problem with 5 outputs**

In [ ]:
X,y = make_regression(n_samples=100,n_features=5, n_targets=5, shuffle=True,random_state=42)

**Looking at the shapes of the feature matrix and label vector**

In [ ]:
X.shape

(100, 5)

In [ ]:
y.shape

(100, 5)

####**Since we generated multi-output target with 5 outputs, the output has shape `(100,5)`**

###`make_classfication`

In [ ]:
from sklearn.datasets import make_classification 
?make_classification

In [ ]:
X,y = make_classification(n_samples =100,n_features=10,n_classes=2,n_clusters_per_class=1,random_state=42) 

In [ ]:
X.shape

(100, 10)

In [ ]:
y.shape

(100,)

In [ ]:
X[:5]

array([[ 0.11422765, -1.71016839, -0.06822216, -0.14928517,  0.30780177,
         0.15030176, -0.05694562, -0.22595246, -0.36361221, -0.13818757],
       [ 0.70775194, -1.57022472, -0.23503183, -0.63604713,  0.62180996,
        -0.56246678,  0.97255445, -0.77719676,  0.63240774, -0.47809669],
       [ 0.63859246,  0.04739867,  0.33273433,  1.1046981 , -0.65183611,
        -1.66152006, -1.2110162 ,  1.09821151, -0.0660798 ,  0.68024225],
       [-0.23894805, -0.97755524,  0.0379061 ,  0.19896733,  0.50091719,
        -0.90756366,  0.75539123,  0.12437227, -0.57677133,  0.07871283],
       [-0.59239392, -0.05023811,  0.17573204, -1.43949185,  0.27045683,
        -0.86399077, -0.83095012,  0.60046915,  0.04852163,  0.32557953]])

In [ ]:
y[:5]

array([1, 1, 1, 1, 0])

**Let's generate a three class classification problem with 100 samples and 10 features**

In [ ]:
X,y = make_classification(n_samples=100,n_features=10,n_classes=3,n_clusters_per_class=1,random_state=42)

In [ ]:
X.shape

(100, 10)

In [ ]:
y.shape

(100,)

In [ ]:
X[:5]

array([[-0.58351628, -1.73833907, -1.37298251, -1.77311485,  0.45918008,
         0.83392215, -1.66096093,  0.20768769, -0.07016571,  0.42961822],
       [-1.0044394 , -1.43862044,  0.47335819, -0.21188291,  0.0125924 ,
         0.22409248, -0.77300978,  0.49799829,  0.0976761 ,  0.02451017],
       [ 0.07740833,  0.19896733,  0.12437227,  0.17738132, -0.97755524,
         0.50091719,  0.75138712,  0.54336019,  0.09933231, -1.66940528],
       [-0.91759569, -0.9609536 ,  1.07746664,  0.4522739 , -0.32138584,
        -0.8254972 , -0.56372455,  0.24368721,  0.41293145, -0.8222204 ],
       [-0.96222828, -0.96090774,  1.21530116,  0.55980482, -1.24778318,
        -0.25256815, -1.43014138,  0.13074058,  1.6324113 , -0.44004449]])

In [ ]:
y[:5]

array([2, 0, 1, 0, 0])

###`make_multilabel_classification`

In [ ]:
from sklearn.datasets import make_multilabel_classification 

In [ ]:
?make_multilabel_classification

In [ ]:
X,y = make_multilabel_classification(n_samples=100,n_features=20,n_classes=5,n_labels=2)
#n_labels =2 ,means average no of labels per example=2

In [ ]:
X.shape

(100, 20)

In [ ]:
y.shape

(100, 5)

In [ ]:
X[:5]

array([[1., 1., 3., 6., 5., 2., 2., 2., 0., 2., 2., 6., 0., 1., 0., 1.,
        3., 5., 7., 1.],
       [0., 1., 6., 0., 7., 7., 1., 1., 2., 2., 2., 4., 1., 1., 2., 1.,
        4., 0., 6., 1.],
       [3., 4., 5., 0., 8., 4., 5., 3., 2., 1., 2., 4., 3., 1., 2., 6.,
        4., 2., 3., 1.],
       [4., 1., 8., 4., 2., 3., 3., 2., 0., 3., 3., 5., 1., 4., 0., 3.,
        1., 3., 4., 0.],
       [2., 1., 6., 2., 2., 2., 2., 1., 2., 5., 1., 2., 1., 3., 2., 2.,
        0., 5., 3., 2.]])

In [ ]:
y[:5]
#whereever 1 means label is present for that datapoint

array([[1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 1, 1]])

###`make_blobs`

**enables us to generate random data for clustering**

In [ ]:
from sklearn.datasets import make_blobs

In [ ]:
?make_blobs

**Let's generate a random dataset of 10 samples with 2 features each for clustering.**

In [ ]:
X, y = make_blobs(n_samples=10,centers=3, n_features=2, random_state=42)

In [ ]:
print("Featrue matrix shape:",X.shape)
print("Label shape:",y.shape)

Featrue matrix shape: (10, 2)
Label shape: (10,)


**We can find the cluster membership of each point in y**

In [ ]:
X

array([[-5.41397842, -7.10588589],
       [-7.42400992, -6.769187  ],
       [ 3.62704772,  2.28741702],
       [-6.81209899, -8.30485778],
       [-2.26723535,  7.10100588],
       [-2.97867201,  9.55684617],
       [-0.92998481,  9.78172086],
       [ 2.914961  ,  1.41088215],
       [ 3.73185476,  0.56086598],
       [-2.97261532,  8.54855637]])

In [ ]:
y

array([2, 2, 1, 2, 0, 0, 0, 1, 1, 0])